name: rebuild and deploy
on: [push]
jobs:
    main:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: cachix/install-nix-action@master
            - name: rebuild
              run: |
                echo $GITHUB_SHA
                nix-build --argstr gitrev $GITHUB_SHA

