name: Auto update from upstream
on:
  schedule:
    - cron: '0 1 * * 0'
jobs:
  update:
    env:
      GH_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@master
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          nix-shell -p nix-prefetch-scripts --run "nix-prefetch-git https://github.com/zoranbosnjak/asterix-specs.git > nix/aspecs.json"
          git add nix/aspecs.json
          update=$(git status --short nix/aspecs.json)
          if [ -n "$update" ]; then
            export ASTERIX_SPECS_REV=$(nix-shell -p jq --run "cat nix/aspecs.json | jq -r '.rev'")
            git commit -m "Periodic sync with asterix-specs #$ASTERIX_SPECS_REV"
            git push
          fi

